### ISSUE TITLE
assert calculator('999.999+=========') == 'error'

### ISSUE THREAD

**Issue by DaredevilSlim** [CheckiO-Missions/checkio-mission-calculator2-5#1]
Please can you explain how it should work for this case and why in this place should return 'error'?

As I understand the behavior should be the next:
first part - "+=" or "-=" - adding/subtracting the number (or operations result) before the combination (doubling the number/subtracting itself);
['999.999', '+', '999.999', '========']
"==" means repeating the last operation;
['999.999', '+', '999.999', '+', '999.999', '======']
"==" means repeating the last operation;
['999.999', '+', '999.999', '+', '999.999', '+', '999.999', '====']
"==" means repeating the last operation;
['999.999', '+', '999.999', '+', '999.999', '+', '999.999', '+', '999.999', '==']
"==" means repeating the last operation;
['999.999', '+', '999.999', '+', '999.999', '+', '999.999', '+', '999.999', '+', '999.999', '']
result
6000.

**Comment by freemanlex** [comment]
Each "=" means repeating the last operation, so you get 9999.99 after rounding to 5 digits 10000 > 5 digits => erorr
